data:
  trainig_data: "./data/model_input/adata_subset_nafld_log1p.h5ad"
  test_data: "./data/model_input/test_data.h5ad"
  imputation_mask: "./data/model_input/imputation_mask.csv"
  
model:
  name: "liver_imputation_v1"
  type: mlp
  n_layers: 3
  raw_layers:
    layer1:
      type: "linear"
      in_dim: 931
      out_dim: 7762 
      activation: "relu"
    layer2:
      type: "linear"
      in_dim: 7762
      out_dim: 15526
      activation: "relu"
    layer3:
      type: "linear"
      in_dim: 15526
      out_dim: 31053
      activation: "relu"

training:
  kfolds: 3
  batch_size: 64
  epochs: 200
  optimizer: "adam"
  loss: "mse"
