[imputation_mask]
type = "csv"
path = "data/imputation_mask.csv"
header = "none"

[train_data]
type = "h5ad"
path = "data/train_data_scRNAseq_train.h5ad"
layer = "log1p"

[test_data.dataset1]
type = "h5ad"
path = "data/train_data_scRNAseq_test.h5ad"
layer = "log1p"

[test_data.dataset2]
type = "h5ad"
path = "data/test_data.h5ad"
layer = "log1p"

[model]
name = "liver_imputation_v1"
type = "mlp"
n_layers = 3

[model.layers.layer1]
type = "linear"
in_dim = 931
out_dim = 7762
activation = "leaky_relu"

[model.layers.layer2]
type = "linear"
in_dim = 7762
out_dim = 15526
activation = "leaky_relu"
dropout = 0.2

[model.layers.layer3]
type = "linear"
in_dim = 15526
out_dim = 31053
dropout = 0.2

[training]
seed = 27062025
kfolds = 5
batch_size = 256
epochs = 500
loss = "mse"

[training.early_stopping]
patience = 20
delta = 0

[training.optimization]
optimizer = "adam"
learning_rate = 1e-3
weight_decay = 1e-4
